version: 1.0.1
files:
  - url: PackClaw-Setup-1.0.1-x64.exe
    sha512: h3Db+DcO2vyWSdoVCHl7D7Lw2AJ4ZIxGhxeYxhyOEyOvhSdyo9jjvOz1PbJ9ZpCUgh4HPV1TPMw+E9GazwIWEg==
    size: 232380976
  - url: PackClaw-Setup-1.0.1-arm64.exe
    sha512: cNMpCLXFippNt5GP5qzypxRHSJi5wxuL0lY3s1+CGA3yzHeB1MmBAXJI8f4++4verHAol1augEktaCuQzZu6ug==
    size: 208803005
releaseDate: '2026-06-04'
